"""Package a trained run for Kaggle code competition inference."""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml


INFERENCE_SCRIPT = r'''#!/usr/bin/env python3
"""Inference-only Kaggle script generated by package_kernel.py."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import lightgbm as lgb
import numpy as np
import pandas as pd
import yaml


def parse_args():
    parser = argparse.ArgumentParser(description="Run Kaggle inference from packaged LightGBM artifacts")
    parser.add_argument("--package-dir", default=".", help="Directory containing model/ and config.yaml")
    parser.add_argument("--data-dir", default=None, help="Competition data directory containing test.csv")
    parser.add_argument("--output", default="submission.csv")
    return parser.parse_args()


def load_config(package_dir: Path) -> dict:
    return yaml.safe_load((package_dir / "config.yaml").read_text(encoding="utf-8")) or {}


def load_test(data_dir: Path) -> pd.DataFrame:
    test_csv = data_dir / "test.csv"
    if not test_csv.exists():
        raise FileNotFoundError(
            f"{test_csv} not found. This generated script currently supports standard CSV competitions. "
            "Directory-style competitions need a competition adapter."
        )
    return pd.read_csv(test_csv)


def apply_preprocessor(X: pd.DataFrame, state: dict) -> pd.DataFrame:
    out = X.copy()
    feature_names = state["feature_names_in"]
    missing = [col for col in feature_names if col not in out.columns]
    if missing:
        raise ValueError(f"missing feature columns for preprocessing: {missing[:5]}")
    out = out[feature_names]

    for col in state.get("numeric_cols", []):
        med = state.get("numeric_medians", {}).get(col)
        if med is not None:
            out[col] = out[col].fillna(med)

    missing_value = state.get("missing_category_value", "__missing__")
    unknown_value = state.get("unknown_category_value", -1)
    for col in state.get("categorical_cols", []):
        categories = state.get("categorical_categories", {}).get(col, [])
        mapping = {value: idx for idx, value in enumerate(categories)}
        out[col] = out[col].fillna(missing_value).map(mapping).fillna(unknown_value).astype(float)
    return out


def predict(model_dir: Path, X: pd.DataFrame) -> np.ndarray:
    manifest = json.loads((model_dir / "manifest.json").read_text(encoding="utf-8"))
    boosters = [lgb.Booster(model_file=str(model_dir / name)) for name in manifest["boosters"]]
    if not boosters:
        raise RuntimeError(f"no boosters found in {model_dir}")
    feature_names = manifest.get("feature_names")
    if feature_names:
        X = X[feature_names]
    return np.mean([booster.predict(X) for booster in boosters], axis=0)


def make_submission(cfg: dict, test_df: pd.DataFrame, preds: np.ndarray, output: Path, preprocess: dict) -> pd.DataFrame:
    data_cfg = cfg.get("data", cfg)
    target = cfg.get("target") or data_cfg.get("target") or preprocess.get("target") or "target"
    id_col = cfg.get("id_col", data_cfg.get("id_col", preprocess.get("id_col")))
    objective = cfg.get("objective") or data_cfg.get("objective") or "regression"
    label_classes = preprocess.get("label_classes")

    if objective == "multiclass" and label_classes is not None:
        target_values = [label_classes[int(i)] for i in np.argmax(preds, axis=1)]
    else:
        target_values = preds

    if id_col and id_col in test_df.columns:
        sub = pd.DataFrame({id_col: test_df[id_col].values, target: target_values})
    else:
        sub = pd.DataFrame({target: target_values})
    sub.to_csv(output, index=False)
    print(f"[kernel] submission saved -> {output} shape={sub.shape}")
    return sub


def main() -> int:
    args = parse_args()
    package_dir = Path(args.package_dir).resolve()
    cfg = load_config(package_dir)
    comp = cfg.get("comp") or cfg.get("competition", {}).get("slug") or cfg.get("data", {}).get("comp")
    data_dir = Path(args.data_dir or f"/kaggle/input/{comp}").resolve()
    model_dir = package_dir / "model"
    preprocess = json.loads((model_dir / "preprocess.json").read_text(encoding="utf-8"))

    test_df = load_test(data_dir)
    data_cfg = cfg.get("data", cfg)
    id_col = cfg.get("id_col", data_cfg.get("id_col", preprocess.get("id_col")))
    X_test = test_df.copy()
    if id_col and id_col in X_test.columns:
        X_test = X_test.drop(columns=[id_col])
    X_test = apply_preprocessor(X_test, preprocess)
    preds = predict(model_dir, X_test)
    make_submission(cfg, test_df, preds, Path(args.output), preprocess)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Package a run as a Kaggle inference dataset/notebook")
    parser.add_argument("--config", default="configs/lgbm_baseline.yaml")
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--output-dir", default="outputs/kernel_packages")
    parser.add_argument("--dataset-id", default=None, help="Kaggle dataset id, e.g. owner/comp-runid")
    parser.add_argument("--title", default=None)
    parser.add_argument("--version-message", default=None)
    parser.add_argument("--create-dataset", action="store_true", help="Run kaggle datasets create/version")
    parser.add_argument("--force-create", action="store_true", help="Use kaggle datasets create even if it exists")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    cfg_path = Path(args.config).resolve()
    cfg = _load_yaml(cfg_path)
    comp = cfg.get("comp") or cfg.get("competition", {}).get("slug") or cfg.get("data", {}).get("comp")
    if not comp:
        raise ValueError("config must define comp or data.comp")

    output_root = Path(cfg.get("runtime", {}).get("output_root", "outputs/runs"))
    run_dir = output_root / comp / args.run_id
    model_dir = run_dir / "model"
    _require(run_dir / "config.yaml")
    _require(model_dir / "manifest.json")
    _require(model_dir / "preprocess.json")

    package_dir = Path(args.output_dir) / comp / args.run_id
    if package_dir.exists():
        shutil.rmtree(package_dir)
    (package_dir / "model").mkdir(parents=True, exist_ok=True)

    shutil.copy2(run_dir / "config.yaml", package_dir / "config.yaml")
    for path in sorted(model_dir.iterdir()):
        if path.is_file():
            shutil.copy2(path, package_dir / "model" / path.name)

    dataset_id = args.dataset_id or _default_dataset_id(comp, args.run_id)
    default_title = f"{comp} {args.run_id} inference package"
    metadata = {
        "title": args.title or default_title[:50],
        "id": dataset_id,
        "licenses": [{"name": "CC0-1.0"}],
    }
    (package_dir / "dataset-metadata.json").write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")
    script_path = package_dir / "kernel_inference.py"
    script_path.write_text(INFERENCE_SCRIPT, encoding="utf-8")
    script_path.chmod(0o755)
    _write_notebook(package_dir / "kernel_inference.ipynb", dataset_id, comp)

    manifest = json.loads((model_dir / "manifest.json").read_text(encoding="utf-8"))
    package_manifest = {
        "competition": comp,
        "run_id": args.run_id,
        "source_run_dir": str(run_dir),
        "dataset_id": dataset_id,
        "model_type": manifest.get("model_type"),
        "n_boosters": manifest.get("n_boosters"),
        "size_bytes": _directory_size(package_dir),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    (package_dir / "package_manifest.json").write_text(
        json.dumps(package_manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"[package-kernel] wrote {package_dir}")
    print(f"[package-kernel] size={package_manifest['size_bytes'] / 1024 / 1024:.2f} MiB")
    if args.create_dataset:
        _publish_dataset(package_dir, dataset_id, args.version_message, force_create=args.force_create)
    else:
        print("[package-kernel] Kaggle dataset publish skipped (pass --create-dataset)")
    return 0


def _load_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _require(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(path)


def _default_dataset_id(comp: str, run_id: str) -> str:
    slug = _slugify(f"{comp}-{run_id}")[:80]
    return f"{_kaggle_username()}/{slug}"


def _kaggle_username() -> str:
    if os.environ.get("KAGGLE_USERNAME"):
        return os.environ["KAGGLE_USERNAME"]
    result = subprocess.run(
        [sys.executable, "-m", "kaggle", "config", "view"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    for line in result.stdout.splitlines():
        if line.strip().startswith("- username:"):
            return line.split(":", 1)[1].strip()
    raise RuntimeError("Kaggle username not found; pass --dataset-id owner/slug")


def _slugify(value: str) -> str:
    out = []
    last_dash = False
    for ch in value.lower():
        keep = ch.isalnum()
        if keep:
            out.append(ch)
            last_dash = False
        elif not last_dash:
            out.append("-")
            last_dash = True
    return "".join(out).strip("-") or "kaggle-model"


def _directory_size(path: Path) -> int:
    return sum(p.stat().st_size for p in path.rglob("*") if p.is_file())


def _publish_dataset(package_dir: Path, dataset_id: str, version_message: str | None, *, force_create: bool) -> None:
    message = version_message or f"package {dataset_id}"
    check = subprocess.run(
        [sys.executable, "-m", "kaggle", "datasets", "status", dataset_id],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    if check.returncode != 0 or force_create:
        cmd = [sys.executable, "-m", "kaggle", "datasets", "create", "-p", str(package_dir), "--dir-mode", "zip"]
    else:
        cmd = [
            sys.executable, "-m", "kaggle", "datasets", "version",
            "-p", str(package_dir),
            "-m", message,
            "--dir-mode", "zip",
        ]
    print(f"[package-kernel] running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)


def _write_notebook(path: Path, dataset_id: str, comp: str) -> None:
    dataset_slug = dataset_id.split("/", 1)[-1]
    code = (
        "import subprocess, sys\n"
        f"package_dir = '/kaggle/input/{dataset_slug}'\n"
        f"data_dir = '/kaggle/input/{comp}'\n"
        "subprocess.check_call([\n"
        "    sys.executable,\n"
        "    f'{package_dir}/kernel_inference.py',\n"
        "    '--package-dir', package_dir,\n"
        "    '--data-dir', data_dir,\n"
        "    '--output', 'submission.csv',\n"
        "])\n"
    )
    notebook = {
        "cells": [
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": code.splitlines(keepends=True),
            }
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    path.write_text(json.dumps(notebook, indent=2), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
